### ISSUE TITLE
Error occuring while passing metadata

### ISSUE THREAD

**Issue by salahvk** [abom-me/thawani_payment#1]
Some Error occuring while passing metadata to thawanipaybtn metadata argument,
    metadata: {"userName": "Nasr Al-Rahbi", "Twitter": "abom_me"},
    this is what i passed , Unhandled Exception: Converting object to an encodable object failed: _Map len:6 and this is the error

**Comment by abom-me** [comment]
I Fixed The bug in version : 0.0.5
Please update The Package.
[Package Link](https://pub.dev/packages/thawani_payment/versions/0.0.5
)

Thank you for using my package

**Comment by junaid4jd** [comment]
@abom-me 

I am getting this error while passing product list.
Error : Unhandled Exception: Converting object to an encodable object failed: _Map len:6
I am using the latest package thawani_payment: ^0.0.6

Product List that i am passing is given below :
[
   {"name": "Product 1", "quantity": 10, "unit_amount": 10},
   {"name": "Product 2", "quantity": 20, "unit_amount": 20}
]
