### ISSUE TITLE
Ontap payment btn

### ISSUE THREAD

**Issue by king99king** [abom-me/thawani_payment#2]
I've updated the package to 0.0.5 and i got same problem "Unhandled Exception: Converting object to an encodable object failed: _Map len:6 "

**Comment by abom-me** [comment]
please share with me  screenshot for the code & the full error

**Comment by king99king** [comment]
![Screenshot 2023-03-10 210742](https://user-images.githubusercontent.com/83115195/224380575-92e87532-0bf5-45c4-9c70-24ec9b4b67bc.png)
`import 'dart:convert';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:thawani_payment/widgets/pay_button.dart';
import 'package:http/http.dart' as http;

import '../../model/InprogressMasjid.dart';
import 'TestScreen.dart';

class paymentScreen extends StatefulWidget {
  const paymentScreen({
    super.key,
    required this.Masjidname,
    required this.PhoneNumber,
    required this.count,
    required this.price,
    required this.totalPrice,
    required this.AdminName,
    required this.Discription,
    required this.LatLocation,
    required this.LogLocation,
    required this.id,
  });
  final String Masjidname;
  final String PhoneNumber;
  final int count;
  final double price;
  final double totalPrice;
  final String AdminName;
  final String Discription;
  final String LatLocation;
  final String LogLocation;
  final String id;
  @override
  State<paymentScreen> createState() => _paymentScreenState();
}

class _paymentScreenState extends State<paymentScreen> {
  late int amount = (widget.price * 1000).toInt();
  late String sessionID = '';

  Future<void> _getRequest() async {
    var body = {
      "client_reference_id": "123412",
      "mode": "payment",
      "products": [
        {
          "name": "${widget.Masjidname}",
          "quantity": widget.count,
          "unit_amount": amount
        },
      ],
      "success_url": "https://company.com/done",
      "cancel_url": "https://company.com/cancel",
      "metadata": {"Customer name": "somename", "order id": 0}
    };

    var url =
        Uri.parse('https://uatcheckout.thawani.om/api/v1/checkout/session');
    var response = await http.post(url,
        headers: {
          'thawani-api-key': 'rRQ26GcsZzoEhbrP2HZvLYDbn9C9et',
          'Content-Type': 'application/json'
        },
        body: json.encode(body));

    try {
      if (response.statusCode == 200) {
        String data = response.body;
        var decodeData = jsonDecode(data);

        setState(() {
          sessionID = decodeData['data']['session_id'];
        });
      } else {
        print('Request failed with status: ${response.statusCode}.');
      }
    } catch (e) {
      print('Exception thrown: $e');
    }
  }

  @override
  void initState() {
    super.initState();
    _getRequest();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Thawani Payment'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              width: 200,
              height: 50,
              child: ThawaniPayBtn(
                testMode: true,
                api: 'rRQ26GcsZzoEhbrP2HZvLYDbn9C9et',
                pKey: 'HGvTMLDssJghr9tlN9gr4DVYt0qyBy',
                clintID: '1234',
                onError: (e) {
                  print(e);
                },
                products: [
                  {
                    "name": "${widget.Masjidname}",
                    "quantity": widget.count,
                    "unit_amount": amount
                  },
                ],
                onCreate: (v) async {
                  await _getRequest();
                },
                onCancelled: (v) {
                  Navigator.pop(context);
                },
                onPaid: (_) async {
                  final Inprogress = InprogressMasjid(
                    name: widget.Masjidname,
                    AdminName: widget.AdminName,
                    Discription: widget.Discription,
                    LatLocation: widget.LatLocation,
                    LogLocation: widget.LogLocation,
                    id: widget.id,
                    Count: widget.count,
                    PhoneNumber: widget.PhoneNumber,
                  );
                  await FirebaseFirestore.instance
                      .collection("InProgress")
                      .add(Inprogress.toJson());
                  Navigator.of(context).pushReplacement(MaterialPageRoute(
                      builder: (BuildContext context) => MapPage()));
                },
              ),
            )
          ],
        ),
      ),
      // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`

**Comment by abom-me** [comment]
### you are using the package in wrong way please follow the document.

## for example:

```dart
 ThawaniPayBtn(
        testMode: true,
        api: 'rRQ26GcsZzoEhbrP2HZvLYDbn9C9et',
        pKey: 'HGvTMLDssJghr9tlN9gr4DVYt0qyBy',
        clintID: '12',
        onError: (e){
          print("----------- Error -------");
          print(e);
          },

        products:[
        {
        "name": "product Name",
        "unit_amount": 100,
        "quantity": 1
        }
        ],

/// metadata As Map<String,dynamic>
        metadata:  {"userName": "User1", "phone": "12345"},


        onCreate: (v) {},
        onCancelled: (v){}
,
        onPaid: (v){
          print(v.success);
        },
      )

```

**Comment by king99king** [comment]
it works, thank you😁
