### ISSUE TITLE
Unhandled Exception: Converting object to an encodable object failed: _Map len:6

### ISSUE THREAD

**Issue by junaid4jd** [abom-me/thawani_payment#3]
@abom-me

I am getting this error while passing product list.
Error : Unhandled Exception: Converting object to an encodable object failed: _Map len:6
I am using the latest package thawani_payment: ^0.0.6

Product List that i am passing is given below :
[
{"name": "Product 1", "quantity": 10, "unit_amount": 10},
{"name": "Product 2", "quantity": 20, "unit_amount": 20}
]

**Comment by abom-me** [comment]
the package updated and the issue are fixed ✅
